# analytics-service runs on port 8086.
# Port plan:
#   8080 - monolith
#   8081 - order-service
#   8082 - inventory-service
#   8083 - payment-service
#   8084 - shipping-service
#   8085 - notification-service
#   8086 - analytics-service  (this one)

server:
  port: 8086

spring:
  application:
    name: analytics-service

  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    com.orderflow: INFO
    org.apache.kafka: WARN